# Generated by Django 5.0.6 on 2024-08-16 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=20)),
                ('CategoryImage', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalDays', models.IntegerField()),
                ('TotalExercises', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgramName', models.CharField(max_length=30)),
                ('ProgramDescription', models.CharField(max_length=500)),
                ('ProgramImage', models.ImageField(blank=True, upload_to='images/')),
                ('TotalDays', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=15)),
                ('TypeDescription', models.CharField(max_length=250)),
                ('TypeImage', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleName', models.CharField(max_length=50)),
                ('ArticleImage', models.ImageField(blank=True, upload_to='images/')),
                ('ArticleText', models.CharField()),
                ('ArticleAuthor', models.CharField(max_length=20)),
                ('CategoryId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='article', to='course.articlecategory')),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AveregeWeight', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('AveregeTall', models.IntegerField()),
                ('MainGoal', models.CharField(choices=[('muscle building', 'muscle building'), ('weight loss', 'weight loss'), ('fitness', 'fitness')], max_length=30)),
                ('PhysicalCondation', models.CharField(choices=[('3-5 pushs', '3-5 pushs'), ('5-7 pushs', '5-7 pushs'), ('7-10 pushs', '7-10 pushs')], max_length=30)),
                ('PlanId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='course.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayName', models.CharField(max_length=20)),
                ('PlanId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='planday', to='course.plan')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedDaysByUserForPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='c1', to=settings.AUTH_USER_MODEL)),
                ('Day', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='c2', to='course.planday')),
            ],
        ),
        migrations.CreateModel(
            name='PlanExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExerciseName', models.CharField(max_length=30)),
                ('ExerciseDescription', models.CharField(max_length=250)),
                ('ExerciseImage', models.ImageField(blank=True, upload_to='images/')),
                ('ExerciseTime', models.IntegerField()),
                ('DayId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='planexercises', to='course.planday')),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExerciseName', models.CharField(max_length=30)),
                ('ExerciseDescription', models.CharField(max_length=250)),
                ('ExerciseImage', models.ImageField(blank=True, upload_to='images/')),
                ('ExerciseTime', models.IntegerField()),
                ('DayId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='course.programday')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedDaysByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cdu1', to=settings.AUTH_USER_MODEL)),
                ('Day', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cdy2', to='course.programday')),
            ],
        ),
        migrations.AddField(
            model_name='programday',
            name='ProgramId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='programday', to='course.programs'),
        ),
        migrations.AddField(
            model_name='programs',
            name='TypeId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='course.types'),
        ),
        migrations.CreateModel(
            name='UserPlanState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComplatedDays', models.IntegerField()),
                
                ('UserName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='upls1', to=settings.AUTH_USER_MODEL)),
                ('UserPlan', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='upls2', to='course.plan')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgrameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComplatedDays', models.IntegerField()),
                ('UserName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ups1', to=settings.AUTH_USER_MODEL)),
                ('UserPrograme', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ups2', to='course.programs')),
            ],
        ),
    ]
