# Generated by Django 5.0.6 on 2024-08-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplanstate',
            name='UserGoal',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
