# Generated by Django 5.0.6 on 2024-08-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_userplanstate_usergoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplanstate',
            name='Gender',
            field=models.CharField(default='', max_length=30),
        ),
    ]
